version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  db:
    image: "postgres:10"
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "hippoboard"
      POSTGRES_PASSWORD: "hippoboard"
