version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  default:
    docker:
      - image: circleci/node:10
      - image: circleci/python:2.7

commands:
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules

jobs:
  build:
    executor: default
    working_directory: ~/hippoboard/ui
    steps:
      - checkout:
          path: ~/hippoboard
      - npm_install

  deploy:
    executor: default
    working_directory: ~/project/ui
    steps:
      - checkout:
          path: ~/hippoboard
      - npm_install
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          from: dist/hippoboard
          to: s3://hippoboard
          overwrite: true

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: test-deploy
