version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "99:e2:bd:ed:c9:11:13:a2:5b:0f:7f:bd:5f:e4:af:ff"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "sudo /etc/deploy.sh"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
