version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  default:
    docker:
      - image: circleci/node:10
      - image: circleci/python:2.7

commands:
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules

jobs:
  build-ui:
    executor: default
    working_directory: ~/hippoboard/ui
    steps:
      - checkout:
          path: ~/hippoboard
      - npm_install

  deploy-ui:
    executor: default
    working_directory: ~/hippoboard/ui
    steps:
      - checkout:
          path: ~/hippoboard
      - npm_install
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          from: dist/hippoboard
          to: s3://hippoboard
          overwrite: true

  deploy-api:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5d:f9:31:cf:df:f3:65:55:56:2b:d8:d8:04:50:e3:d0"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "sudo /etc/deploy.sh"

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build-ui
      - deploy-ui:
          requires:
            - build-ui
          filters:
            branches:
              only: test-deploy
      - deploy-api:
          filters:
            branches:
              only: test-deploy
