#########################################################
# Wordpress on Amazon Linux LEMP
#########################################################

---
- hosts: all
  roles:
    - common

- hosts: web
  roles:
    - nginx
    - postgres
    -
      role: deploy
      tags: deploy
    -
      role: go
      tags: go
