---
- name: Install Nginx
  command: amazon-linux-extras install nginx1.12 -y
  ignore_errors: true

- name: Ensure Nginx is started
  service:
    name: nginx
    state: started
    enabled: true

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_user }}"
    mode: '0755'

- name: Copy Nginx default Configuration
  template:
    src: "roles/nginx/files/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify: restart nginx

- name: Set up Nginx VirtualHost
  template:
    src: "roles/nginx/files/{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ item }}"
  loop:
    - "{{ main_host }}.conf"
    - "{{ sub_host }}.conf"
  notify:
    - restart nginx
    - restart php
