---
- name: Enable php7.4 repo
  command: amazon-linux-extras install php7.4 -y
  ignore_errors: true

- name: Install PHP modules
  yum:
    name: "{{ item }}"
    enablerepo: amzn2extra-php7.4
    state: present
  loop: "{{ php_modules }}"

- name: Ensure php-fpm is started
  service:
    name: php-fpm
    state: started
    enabled: true

- name: Copy php.ini
  copy:
    src: "roles/php/files/php.ini"
    dest: "/etc/php.ini"
    backup: yes
  notify: restart php

- name: Copy www.conf
  template:
    src: "roles/php/files/www.conf.j2"
    dest: "/etc/php-fpm.d/www.conf"
  notify: restart php
