version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:80
  db:
    image: "postgres:10"
    container_name: "postgres"
    ports:
      - "54320:5432"
    volumes:
      - hippoboard_db_vm:/var/lib/postgresql/data
volumes:
  hippoboard_db_vm:
