---
- name: Copy deploy script
  copy:
    src: "roles/deploy/files/deploy.sh"
    dest: "/etc/deploy.sh"

- name: Create the docroot
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    mode: 0755

- name: Clone the code repository to the docroot
  git:
    repo: "{{ git_repo }}"
    dest: "/var/www/{{ http_host }}"
    accept_hostkey: yes

- name: Set ownership
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_user }}"

- name: Set permissions for directories
  shell: "find /var/www/{{ http_host }}/ -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  shell: "find /var/www/{{ http_host }}/ -type f -exec chmod 640 {} \\;"
  notify: restart nginx
